# Generated by Django 2.0.7 on 2018-07-09 03:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章类型', 'verbose_name_plural': '文章类型'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='order_index',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=150, null=True, verbose_name='文章来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
